### PR TITLE
Ported gendb to py3

### PR DESCRIPTION
**Pull request by 0xfabi**
Hi Sander,

I've ported everything from /xml_db to python3. Please let me know if the code works like expected.

### CODE REVIEW

**Comment by svdhoog** [comment]
This is to be tested, and when all ok, then merged into master branch of main repo.

**Comment by svdhoog** [comment]
@0xfabi 

1. The porting of gendb.py to python3 did not yet work correctly.
I ran the old gendb.py using python2 on the same XML files to check this.

Error output:
```
Traceback (most recent call last):
  File "gendb.py", line 263, in <module>
    load_iteration_file(i, itsdir, db)
  File "gendb.py", line 108, in load_iteration_file
    db.execute( get_agent_sql(data) ) # store data in db
sqlite3.OperationalError: near "minsky_state_40": syntax error
```
The variable `minsky_state_40` is well-defined in the `model.xml,` as well as outputted in the `20.xml` file. 

2. Please also port gendb_special.py to python3 (probably best to first fix gendb.py, and then do a diff with the gendb_special.py, since the changes are minimal).

**Comment by svdhoog** [comment]
After the latest changes of -p to -x, and the addition of the output folder creation, I get this error for both gendb.py and gendb_special.py:
```
Traceback (most recent call last):
  File "gendb.py", line 140, in <module>
    if args.outputpath[0].rsplit('/', 1)[1].endswith('.db'):
AttributeError: 'Namespace' object has no attribute 'outputpath
```
- With output argument:
```
$ python3 gendb.py -o ./output/out.db -m ../../../../../../GitLab/ETACE-Conquaire/model_code/Financial_Fragility_Network_Model_2.0/eurace_model.xml -x ../../../../../..//GitLab/ETACE-Conquaire/Final_format/data/gamma_scenarios/xml/set_3/run_test/
```
- Without output argument:
```
$ python3 gendb.py -m ../../../../../../GitLab/ETACE-Conquaire/model_code/Financial_Fragility_Network_Model_2.0/eurace_model.xml -x ../../../../../../GitLab/ETACE-Conquaire/Final_format/data/gamma_scenarios/xml/set_3/run_test/
```

**Comment by svdhoog** [comment]
Also: full usage example for gendb in usage_help.rst needs to be updated from -p to -x

**Comment by 0xfabi** [comment]
I have fixed the error for both gendb scripts.
I've also added a check if the output directory exists.

**Comment by svdhoog** [comment]
DONE!

**Pull request merged**
